kind: Service
apiVersion: v1
metadata:
  name: crawler-service
spec:
  selector:
    app: crawler-service
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-service
spec:
  selector:
    matchLabels:
      app: crawler-service
  replicas: 1
  template:
    metadata:
      labels:
        app: crawler-service
    spec:
      containers:
        - name: crawler-service
          image: crawler-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: crawler-db-config
                  key: database
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: crawler-db-config
                  key: host