apiVersion: v1
kind: Service
metadata:
  labels:
    app: crawlerdb
  name: crawlerdb-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: crawlerdb
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawlerdb
  labels:
    app: crawlerdb
spec:
  selector:
    matchLabels:
      app: crawlerdb
  replicas: 1
  template:
    metadata:
      labels:
        app: crawlerdb
      name: crawlerdb-service


    spec:
      containers:
        - image: mongo:latest
          name: crawlerdb

          ports:
            - containerPort: 27017
              name: crawlerdb